name = "lean4lean"
defaultTargets = ["Lean4Lean", "lean4lean", "Lean4Lean.Theory", "Lean4Lean.Verify"]

[[require]]
name = "batteries"
git = "file:///Users/alokbeniwal/tmp/batteries"
rev = "dc3c53dff5421d6f09e7f19eae0b48881d8343a1"

[[lean_lib]]
name = "Lean4Lean"

[[lean_lib]]
name = "Lean4Lean.Theory"
globs = ["Lean4Lean.Theory.*"]

[[lean_lib]]
name = "Lean4Lean.Verify"
globs = ["Lean4Lean.Verify.*"]

[[lean_lib]]
name = "Lean4Lean.Experimental"
globs = ["Lean4Lean.Experimental.+"]

[[lean_exe]]
name = "lean4lean"
root = "Main"
supportInterpreter = true
